<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CC Email_ccEmail</name>
   <tag></tag>
   <elementGuidId>e214b736-66d0-4139-8268-cf2d99b1135a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ccEmail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ccEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4a90024a-d606-4fe3-bfcc-fb7f11e79935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bd4c52c6-d2ec-4470-9d74-ca211b95d81e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ccEmail</value>
      <webElementGuid>1ffdf5dc-18ca-40c2-b545-ab7e67840d9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ccEmail</value>
      <webElementGuid>6f2c4ff4-4d1d-460e-b2a4-b9cdb6918d49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter email</value>
      <webElementGuid>ebe02b1c-5b25-4744-8ba7-1c72f42e3afc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>45f1a754-6a9c-49e4-8652-499327576225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiOutlinedInput-input MuiInputBase-input MuiInputBase-inputSizeSmall css-ch4d73</value>
      <webElementGuid>9a633f44-a6bf-49df-94f4-992b118e3ed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>''@mail.com</value>
      <webElementGuid>983c10b8-3e6b-434b-accb-bd957f507828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ccEmail&quot;)</value>
      <webElementGuid>026c3ed9-0aa5-46f5-b7d3-4f8e31d5ac09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ccEmail']</value>
      <webElementGuid>e8786c6c-2abe-4b13-9374-56334b11c576</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div[2]/div/div/div[2]/form/div/div[2]/div/div/input</value>
      <webElementGuid>61d95cce-a441-48e5-9e44-af9aa6467382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div/div/input</value>
      <webElementGuid>0f96700e-85ac-420b-9e9d-cca096096601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ccEmail' and @name = 'ccEmail' and @placeholder = 'Enter email' and @type = 'text']</value>
      <webElementGuid>30c2b7d9-8792-4f01-a710-6270abf77a27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
