<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnDecline</name>
   <tag></tag>
   <elementGuidId>1115e6a5-db42-4881-a491-7fc8c6e05632</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button)[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
