<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_address1</name>
   <tag></tag>
   <elementGuidId>f2fdae58-483f-4389-a0db-f594946d38dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#billing_info-address1</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
