<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>KO-1870 Show pending invitation in License Management page (KSE per-User)</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>e3275094-bcf0-495e-a1ac-06c6473e530d</testSuiteGuid>
   <testCaseLink>
      <guid>a8bc363c-f247-4882-9382-72774084997a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/KatOne/Org Level/License Management/Show Pending Invitation</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>00e5a220-ee1b-4ecd-86d6-8a93eea2009b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dfea3e1e-1fcf-4d6c-838a-3adbdd6cd6fc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>43b34b95-3dec-409d-8aae-b00d8c366689</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/KatOne/Org Level/User Management/Revoke Invitation</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d8cf956f-fb96-47ca-ac59-0e017bc277dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>01248226-0103-4ff0-a10d-4f8bec4b6e2d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1095c73a-ffd8-4684-8174-aaffdb32d6ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>636dbe47-596c-4323-b164-c66656f7b276</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b8b2e050-31e6-4694-a134-1fc2dcc6710a</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
