<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Org Name</name>
   <tag></tag>
   <elementGuidId>3bdfa789-749c-44b3-a789-af59b63e586c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-6</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;mui-6&quot;)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[contains(@class,'MuiFormControl')])[2]//input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>32debd73-87f4-4354-8b6a-595aeae662bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a103c967-6caf-470e-8b76-bc2a6dbe4732</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your Account name</value>
      <webElementGuid>cc535379-d928-442c-ab6a-1595f7ad6542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>674fe54c-18a8-46d1-9f92-9c2c3fbf8133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>c8a79fcf-6e16-4860-84e5-27606558ffa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiOutlinedInput-input MuiInputBase-input MuiInputBase-inputHiddenLabel css-1sxenmq</value>
      <webElementGuid>d08aa491-d57b-4e3c-9eba-b15d22054ff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-6</value>
      <webElementGuid>cfc0397a-e4a0-4289-ad26-6b0aef21ed87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-6&quot;)</value>
      <webElementGuid>cab4258c-4cce-490d-b796-ecac39f42579</webElementGuid>
   </webElementProperties>
</WebElementEntity>
