<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Katalon TestCloud Overview</name>
   <tag></tag>
   <elementGuidId>25d89f6b-cd52-46d2-a81b-03b61cac8dca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div[2]/div[2]/div/div[2]/p[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0d44eca9-d7be-4fdc-8f6d-d2e629202c04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-inherit MuiLink-root MuiLink-underlineNone jss72 css-1b45jtj</value>
      <webElementGuid>39fa69b3-3e41-4fde-9e9f-b2c7608c56f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://docs.katalon.com/docs/katalon-testcloud/testcloud-overview</value>
      <webElementGuid>8a904f45-34e6-402a-b4d2-452953ff062b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Katalon TestCloud Overview</value>
      <webElementGuid>bd315322-b4de-431e-901f-f0a0db9e7234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;jss13&quot;]/div[@class=&quot;jss31&quot;]/div[@class=&quot;jss32 MuiBox-root css-0&quot;]/div[@class=&quot;jss53 MuiBox-root css-0&quot;]/div[@class=&quot;jss69 MuiBox-root css-x4dmss&quot;]/div[@class=&quot;jss71 MuiBox-root css-0&quot;]/div[@class=&quot;jss70 MuiBox-root css-x4dmss&quot;]/p[@class=&quot;MuiTypography-root MuiTypography-body2 jss74 css-1ems3uu&quot;]/a[@class=&quot;MuiTypography-root MuiTypography-inherit MuiLink-root MuiLink-underlineNone jss72 css-1b45jtj&quot;]</value>
      <webElementGuid>34acb982-30eb-4d0c-b8fc-1bea4ad4979a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div[2]/div[2]/div/div[2]/p[2]/a</value>
      <webElementGuid>375863cb-0dfb-4b71-bd26-e97cbebee184</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Katalon TestCloud Overview')]</value>
      <webElementGuid>8fdeced4-c046-4bf6-a6e6-870ad9051040</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Katalon TestOps Overview'])[1]/following::a[1]</value>
      <webElementGuid>95e1fd58-b969-4c2b-9ca1-daf3308dc845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Katalon Runtime Engine Introduction'])[1]/following::a[2]</value>
      <webElementGuid>4bd7a0c9-8412-4c81-bc5d-fe960c9e73ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Katalon Recorder Overview'])[1]/preceding::a[1]</value>
      <webElementGuid>1ef3f9ef-2887-45c9-87df-ad544485cf43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Katalon TestCloud Overview']/parent::*</value>
      <webElementGuid>c67bd6d5-6d57-4c18-8edd-0b6972aa4708</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://docs.katalon.com/docs/katalon-testcloud/testcloud-overview')]</value>
      <webElementGuid>f148ef97-53ee-49e3-9886-825109220049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p[2]/a</value>
      <webElementGuid>efbe2712-a739-4715-bb06-3872957c1064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://docs.katalon.com/docs/katalon-testcloud/testcloud-overview' and (text() = 'Katalon TestCloud Overview' or . = 'Katalon TestCloud Overview')]</value>
      <webElementGuid>d87527bd-988f-42be-977f-632db4518602</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
