<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h6_account name</name>
   <tag></tag>
   <elementGuidId>910a3131-25b1-48d4-949f-77a5c3b8b485</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h6.MuiTypography-root.MuiTypography-subtitle2.jss121.css-zd8ipc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div/div/div/div/div/h6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h6</value>
      <webElementGuid>5416df6f-612c-4eed-afce-0db270dbb2f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-subtitle2 jss121 css-zd8ipc</value>
      <webElementGuid>5cf8108e-d9db-40e0-8716-d37f2f6b5df9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>test</value>
      <webElementGuid>d291b2ce-22c5-4cc3-bea5-476f558693c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>test</value>
      <webElementGuid>c603f5d9-0f3d-4700-8b9c-54797325f5f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;jss93&quot;]/div[@class=&quot;jss111&quot;]/div[@class=&quot;jss112 MuiBox-root css-0&quot;]/div[@class=&quot;jss113 MuiBox-root css-0&quot;]/div[@class=&quot;jss117 MuiBox-root css-x4dmss&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation1 jss120 css-1xkwv0t&quot;]/div[@class=&quot;jss118 MuiBox-root css-0&quot;]/div[@class=&quot;jss119 MuiBox-root css-0&quot;]/h6[@class=&quot;MuiTypography-root MuiTypography-subtitle2 jss121 css-zd8ipc&quot;]</value>
      <webElementGuid>41f432b9-d10a-4559-a79c-15026a6479f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/div/div/div/h6</value>
      <webElementGuid>2e6ffae2-75d0-4fc5-aad3-63b0604686e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='test']/parent::*</value>
      <webElementGuid>31e53888-9b6c-422f-9dd3-47e313837ca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h6</value>
      <webElementGuid>84e3f8d7-93bb-49a2-84d6-cf8db6fb4e55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h6[@title = 'test' and (text() = 'test' or . = 'test')]</value>
      <webElementGuid>e4360e6e-2e80-47f7-a92e-cf4afd5dcc22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
